# Generated by Django 3.2.7 on 2021-09-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=50, verbose_name='Sabor')),
            ],
        ),
        migrations.CreateModel(
            name='PartsOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Parte del producto')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.flavor')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.partsofproduct'),
        ),
    ]
