# Generated by Django 3.2.7 on 2021-09-28 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='orderFlavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.flavor'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderFlavorBizcocho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.flavorbizcocho'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderFlavorCoverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.flavorcoverage'),
        ),
    ]
