# Generated by Django 3.2.7 on 2021-09-24 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210924_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='partsOfProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='cobertor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.flavor'),
        ),
    ]
