# Generated by Django 3.2.7 on 2021-10-16 20:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='orderFlavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.flavor'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderFlavorBizcocho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.flavorbizcocho'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderFlavorCoverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.flavorcoverage'),
        ),
        migrations.CreateModel(
            name='OrderFlavorCookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=6, null=True, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(36)])),
                ('orderFlavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.flavor')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.orderitem')),
            ],
        ),
    ]
