# Generated by Django 3.2.7 on 2021-09-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210924_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cobertor',
        ),
        migrations.AddField(
            model_name='product',
            name='cobertor',
            field=models.ManyToManyField(blank=True, null=True, to='products.Flavor'),
        ),
    ]
