# Generated by Django 3.2.7 on 2021-09-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210924_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cobertor',
            field=models.ManyToManyField(blank=True, to='products.Flavor'),
        ),
    ]
