# Generated by Django 3.2.7 on 2021-10-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211016_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderflavorcookies',
            name='orderFlavor',
        ),
    ]
