# Generated by Django 3.2.7 on 2021-09-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_cobertor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bizcocho',
            field=models.ManyToManyField(blank=True, related_name='bizcocho', to='products.Flavor', verbose_name='cobertor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cobertor',
            field=models.ManyToManyField(blank=True, related_name='cobertor', to='products.Flavor', verbose_name='cobertor'),
        ),
    ]
