# Generated by Django 3.2.7 on 2021-10-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_orderflavorcookies_orderflavor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderflavorcookies',
            name='orderFlavor',
        ),
    ]
