# Generated by Django 3.2.7 on 2021-09-24 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210924_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bizcocho',
        ),
        migrations.AddField(
            model_name='product',
            name='bizcocho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bizcocho', to='products.flavor', verbose_name='cobertor'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='cobertor',
        ),
        migrations.AddField(
            model_name='product',
            name='cobertor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobertor', to='products.flavor', verbose_name='cobertor'),
        ),
    ]
