# Generated by Django 3.2.7 on 2021-10-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_orderflavorcookies_orderflavor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderflavorcookies',
            old_name='quantity',
            new_name='quantitycook',
        ),
    ]
