# Generated by Django 3.2.7 on 2021-09-24 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210924_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composicion', to='products.flavor', verbose_name='composicion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bizcocho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bizcocho', to='products.flavor', verbose_name='bizcocho'),
        ),
    ]
