# Generated by Django 3.2.7 on 2021-09-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210924_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartsOfProduct',
        ),
    ]
