# Generated by Django 3.2.7 on 2021-10-16 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_quantity_orderflavorcookies_quantitycook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderflavorcookies',
            old_name='quantitycook',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='orderflavorcookies',
            name='orderItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderFlavorCookies', to='products.orderitem'),
        ),
    ]
