# Generated by Django 3.2.7 on 2021-09-24 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_partsofproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bizcocho',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cobertor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='composicion',
        ),
        migrations.AddField(
            model_name='flavor',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='products.product'),
        ),
    ]
