# Generated by Django 3.2.7 on 2021-10-16 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211016_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderflavorcookies',
            name='orderFlavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderFlavorCookies', to='products.flavor'),
        ),
    ]
