# Generated by Django 3.2.7 on 2021-09-24 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210924_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bizcocho', to='products.product'),
        ),
    ]
