# Generated by Django 3.2.7 on 2021-09-24 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_flavor_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flavor', to='products.product'),
        ),
        migrations.CreateModel(
            name='FlavorCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=50, verbose_name='Sabor de cobertura')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flavorCoverage', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='FlavorBizcocho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=50, verbose_name='Sabor de bizcocho')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flavorBizcocho', to='products.product')),
            ],
        ),
    ]
